//
// Created by noahs on 4/15/26.
//

#ifndef FINALPROJECT_ACCOUNTTYPEENUM_H
#define FINALPROJECT_ACCOUNTTYPEENUM_H


enum class AccountTypeEnum {STUDENT, FACULTY, STAFF};


#endif //FINALPROJECT_ACCOUNTTYPEENUM_H